YALB-476: Wire Image Paragraph
yalesites-org/yalesites-project pull request #20
Opened 2022-04-29 15:34 UTC by ModulesUnraveled

## [YALB-476: Wire Image Paragraph](https://yaleits.atlassian.net/browse/YALB-476)

### Description of work
- Wires the Image paragraph type

### Functional testing steps:
- [ ] Log in to the site https://pr-17-yalesites-platform.pantheonsite.io/user/login
- [ ] [Create a page](https://pr-17-yalesites-platform.pantheonsite.io/node/add). Fill in the title and add an "Image" component (with caption).
- [ ] Save the page, and verify the image and caption render on the page as expected ("content-width" wrapped in a `<figure>` tag)
- [ ] Edit the page, and remove the caption
- [ ] Save the page, and verify the image is just an `<img>` tag now, without the figure markup. But that it's still "content-width".

2022-04-30 04:11 UTC, nJim commented on scripts/local/setup.sh
> +  echo "Excluding composer.lock to keep it out of the repo."
Thanks 👍

2022-04-30 04:21 UTC, nJim approved these changes
Completes code review. Yaml files are easy. Everything looks great.

2022-05-02 16:54 UTC, ahitson commented
Note to add cropping ticket.

2022-05-02 16:55 UTC, ahitson approved these changes

2022-05-03 17:00 UTC, miketullo95 approved these changes
This works great! 

I had one small hiccup with the last two image files in the test environment where they would not show up after saving. They are blank in the grid view as shown in SS but show up in the table view... odd 🤷 
![Screen Shot 2022-05-03 at 12 58 19 PM](https://user-images.githubusercontent.com/98550395/166502699-9384fdff-9fb3-4bcf-a747-c5c2c2a0a2f5.png)

2022-05-03 17:33 UTC, kara-franco requested changes
Very nice! The only item I saw that needs a tweak is:

- [ ] the aria-label on the <figure> has some extra content coming in. In the example below, the aria-label should read "aria label is working"

<img width="908" alt="Screen Shot 2022-05-03 at 1 32 14 PM" src="https://user-images.githubusercontent.com/12991593/166507642-94c2dadb-1882-4f7b-bb6a-2b806f648f55.png">

2022-05-03 22:09 UTC, kara-franco approved these changes

2022-05-03 23:18 UTC, merged