YALB-1198: Events: Exposed filters on dynamic list (BE)
yalesites-org/yalesites-project pull request #276
Opened 2023-05-17 20:23 UTC by codechefmarc

## [YALB-1198: Events: Exposed filters on dynamic list (BE)](https://yaleits.atlassian.net/browse/YALB-1198)

### Description of work
- Adds event category taxonomy vocabulary
- Adds event category exposed filter to calendar list - limits terms to only ones in use
- Adds event category filtering to views basic - visible only when event is selected
- Adds operator (AND/OR) functionality to views basic
- Allows multiple terms to be selected / filtered on for tags and event categories (hence why operator was added)
- Adds "No results found." message to view if no results are found.

### Functional testing steps:
- [ ] 
- [ ] Step 2
- [ ] Step 3
- [ ] ...

2023-05-18 13:12 UTC, dblanken-yale commented
@codechefmarc In the first step, I'm unable to visit the first link `event_category/add`; it says I don't have access with my CAS login--is that intended for our non-admin access level?  I can get to the overview.

2023-05-19 16:15 UTC, dblanken-yale commented
Great work.  I finished testing the rest then.  Really liking the filtering.  Not sure if you want to wait for Jim but looks good to me.  :D

2023-05-19 16:15 UTC, dblanken-yale approved these changes

2023-05-19 23:14 UTC, codechefmarc commented
@joetower - OK, I was able to theme the filter form and would like your eyes on the code, specifically in atomic and component library. Here's what I did:
- CSS is in `01-atoms/forms/_yds-form.scss` (Is this the best place to put it? Was the class I added appropriate?)
- Added a new `block` in `03-organisms/card-collection/yds-card-collection.twig` that is for adding filters if they exist and to place them below the heading and above the results.
- Updated `atomic/templates/views/views-view--event-list.html.twig` to add the filters into that new block.

Thank you!

2023-05-23 22:31 UTC, joetower commented
@codechefmarc This is looking good to me! 

I pushed up a couple changes to the [component-library](https://github.com/yalesites-org/component-library-twig/pull/243) and one template addition to the [atomic branch](https://github.com/yalesites-org/atomic/pull/127/commits/bda28c5c0d4447fcc78991c048a5c12b6fa8855c). 

Could you please give my changes a look and make sure everything looks good to you? 

https://pr-276-yalesites-platform.pantheonsite.io/dave-events

2023-05-24 13:47 UTC, codechefmarc commented
@joetower - thank you for your edits/additions to the component library and atomic! I tested all of that locally and it worked great. I'm going to do a little accessibility additions before merging.

2023-05-24 13:53 UTC, joetower commented
@codechefmarc Sound great! I'm actually thinking I'm going to change the dropdown icon to the angle-down svg. I'm going to push another fix to the component-library branch and will let you know when my fix has been pushed over there.

2023-05-24 15:52 UTC, joetower commented
@codechefmarc Okay, I pushed up my fixes to the component-library and rebuilt the mutlidev :partying_face: 
https://pr-276-yalesites-platform.pantheonsite.io/dave-events

2023-05-26 04:24 UTC, nJim commented on package.json
> +    "@drupal/autocomplete": "^0.0.2"
Remove unused dependency.

2023-05-26 14:42 UTC, nJim requested changes
The combination of any/all terms is working. We're about to introduce a lot more in the filters section, especially with the introduction of news and profiles. Once the other content types catch up, maybe we can crawl through this code and see if there is room to reorganize. Right now it's perfect.
 
Just one change -- something related to my early contribution. The new field is rendering on Event nodes. Can you please remove the category field from the node? We may add it in the future, but right now it is just out of place and unstyled. (https://pr-276-yalesites-platform.pantheonsite.io/admin/structure/types/manage/event/display/default/layout)

2023-05-26 19:02 UTC, nJim approved these changes
I made a quick change to update the display. So this is ready to go. Shipping.

2023-05-26 19:02 UTC, merged