fix(YALB-1562): remove global themes 4 and 5
yalesites-org/yalesites-project pull request #441
Opened 2023-09-28 17:48 UTC by joetower

## [YALB-1562 - Color: Update tokens for existing color palettes](https://yaleits.atlassian.net/browse/YALB-1562)

### Description of work
- Remove themes `four` and `five`

![New Color Palettes](https://github.com/yalesites-org/tokens/assets/366413/a44e9749-c8d3-49ec-b00b-ca2fc5fedc62)

### Functional testing steps:
- [ ] Visit
- [ ] Verify you see the new color themes

2023-10-02 16:27 UTC, codechefmarc requested changes
The initial options look good. However, when I changed the global theme to shoreline summer, then I go to the button theme picker, the options are still the older options and then if I choose the different button themes, the button on the page does change to the correct shoreline summer colors.

![Screenshot 2023-10-02 at 9 25 53 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/31dbd8f6-ec0d-4f9f-8671-48f97b9140d4)

![Screenshot 2023-10-02 at 9 25 58 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/f2dfd0c2-108b-4b60-811f-ff37cf6c9909)

![Screenshot 2023-10-02 at 9 26 01 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/085feb7f-4009-4758-a349-d07616866937)

2023-10-02 16:29 UTC, joetower commented
@codechefmarc 😆 I just noticed this, as well. 

I just pushed a fix. The button_themes will now (when it's done rebuilding) properly display options `one` through `seven` and show the correct colors.

2023-10-02 21:26 UTC, codechefmarc approved these changes
Sweet, that change fixed it. Looks great! Approved!

2023-10-03 10:50 UTC, nJim approved these changes

2023-10-03 10:50 UTC, merged