YALB-520: Links: Dynamically apply link treatments
yalesites-org/yalesites-project pull request #467
Opened 2023-10-27 15:39 UTC by dblanken-yale

## [YALB-520: Links: Dynamically apply link treatments](https://yaleits.atlassian.net/browse/YALB-520)

### Description of work
- Adds javascript sprinkles to identify and modify links on page to match component-library-twig links

### Functional testing steps:
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] ...

2023-11-10 00:09 UTC, codechefmarc commented
@dblanken-yale - I did some testing with this today and here are some of my notes:
- First off great work on this! I would love a tour of the code at some point. I tried to follow some of the JS's and got a little bit lost in how it picks from the different formatters. But neat stuff!
- My tests: See https://pr-467-yalesites-platform.pantheonsite.io/yalb-520
- External - worked
- New Window - didn't work initially because the editor was stripping out the `target` attribute. I added that in (to the multidev only, this is a larger issue that is being addressed in another ticket). So, even with `target` attribute there, it is not getting the link treatment.
- Document - didn't work
- Mailto - worked
- Tel: worked
- Anchor - was this to add the chevron? It didn't work though

I'm happy to do some additional testing if you need. I didn't test other components at this time, but can in subsequent tests.

2023-11-10 13:52 UTC, dblanken-yale commented
@codechefmarc Thanks a lot for trying it out.  Ya, I was hoping I'd not have to set a weight to each evaluation, but it is looking like that will be the case.  ☹️ 

I'll implement new window implementation since at the time we weren't allowing it.  Thanks for pointing that out.

Ya I think the ones that didn't work are receiving the internal link treatment first.  Once I get the weights in, it'll be fine I bet.  I'll ping ya to look at your page when it's all done since it shouldn't affect the creation of those links.

I'd be happy to run through the evaluator/render logic whenever you have time.

2023-11-10 14:24 UTC, dblanken-yale commented
@codechefmarc Actually, I did implement the include_blank, but I remember now that I couldn't test it because CKE was removing the blank targets.  With your new module I saw you talking about, it will be included?  How did you get it included in the multidev before that module got in?  I try to do that locally using source and it removes it before my evaluator can get to it.

2023-11-10 16:04 UTC, dblanken-yale commented
@codechefmarc I was able to get target working by modifying the Basic_HTML config to allow target as both an editing and rendering option for the `a` tag.  But that seems more related to your change of adding the option in CKE to have targets, right?  Should I enable it here?  I did do it locally and it decorates fine now that we have weights.  I didn't know thought if it was appropriate to have here since it'd allow users to put targets in before we truly allowed them.

2023-11-13 17:15 UTC, codechefmarc commented
@dblanken-yale - The new module that I mentioned isn't going in until later whenever that ticket (YALB-1368) gets worked on. So I did what I think you did - temporarily modify the basic HTML format on the multidev to allow the `_blank` attribute on links. I just tested it again, and it looks like both all of them are working now!

Yah, since we have both standup and grooming today, perhaps either after grooming or tomorrow we can go over the code. Thanks!

2023-11-14 18:54 UTC, codechefmarc requested changes
Ok, did a bunch more testing with more blocks, inline links, etc. All tested great with the exception of the following:

- All tests are here: https://pr-467-yalesites-platform.pantheonsite.io/yalb-520

- Not sure if this is intended or not (based on ordering of the processors) but an external document PDF works fine, but an external new window document only gets the new window treatment. I think that's fine, but wanted to point it out:

![Screenshot 2023-11-14 at 10 49 13 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/3f7ab2ff-1e09-4578-9fcf-8da6833509b2)

- Bug: When adding a telephone in the list, it worked with the copy button, but oddly, when inline with other text, it was copying the wrong thing. I.e. the phone number to copy is 123-456-6789, but it copied "test@example.com".

![Screenshot 2023-11-14 at 10 50 50 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/f85523bb-edb6-405c-b000-7e9ceb8ef511)

- Not sure if this a bug? Copy feature does not work within a media modal caption:

![Screenshot 2023-11-14 at 10 52 14 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/243c9910-67c8-4c95-a2db-d787cbbb7863)

- Bug: Grand Hero adds a copy button for an email address and looks strange:

![Screenshot 2023-11-14 at 10 52 44 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/dd04cb46-48fb-4b1c-862c-fdca8e9697c1)

- Bug tabs: getting strange line through the tab, not sure if this is something based on your work or an existing bug, but probably talk with Joe about that one:

![Screenshot 2023-11-14 at 10 54 07 AM](https://github.com/yalesites-org/yalesites-project/assets/107938318/d450b4b2-143c-41c7-b38b-a616879ade60)

2023-11-14 21:33 UTC, dblanken-yale commented
@codechefmarc Nice work!  Thanks so much for testing it so much!  I suspect it is due to the order of the processors in the case you mentioned of the external link.  I think I should get some feedback on what "should" win out on really all of them.

The copy functionality is now working--I attempted to use an unmodified version of the copy from storybook, but it seems in these cases, there is no parent that would contain the two elements that are interacting (which that JS version was expecting), so I had to change it to target it's previous sibling.  In my tests, the p tag was the parent so I think that's why it worked before.  They should all now work.  (Well, once Pantheon is able to do a new deploy to the multidev--looks like quay.io is having issues currently)

Looking at the grand hero, it looks as if it has specific special classes to handle itself, so I am excluding that from being treated.  The same goes for the tabs--it is attempting to treat it when it doesn't need it.

All of those fixes have been pushed, although the build currently isn't able to do so.  I'll let everyone know once it is, and will try to test even more controls to make sure I've excluded all I can.

2023-11-21 21:50 UTC, dblanken-yale commented
I believe this is ready for a re-review.  It looks like the order of the evaluations in teams are sound, so I think we can go forward with it as is?

2023-11-22 13:54 UTC, dblanken-yale commented
The latest "revert" of the "revert" was to implement a change the accessibility team wanted to see as a way to determine whether the copy button's toggle-back event should be done, or if it should stay with a static message instead.

If this is accepted, I'll be creating a ticket for the component library change to mirror this.

2023-11-27 22:44 UTC, joetower commented
@dblanken-yale This is looking great! Awesome work.  

I noticed, on this page, `table` links aren't awesome: https://pr-467-yalesites-platform.pantheonsite.io/testing-all-of-the-things. We could add `table a.link--with-icon.ys_linked {display: inline;}` to fix this. I feel as though everything else is looking good. I'll keep testing a bit, though. 👍 

https://github.com/yalesites-org/yalesites-project/assets/366413/39e84b6c-6a74-4097-87da-23a3e9197bf4

2023-11-28 13:32 UTC, dblanken-yale commented
@joetower Ouch, outstanding find.  I'll try that inline since that's similar to what we did with links in general to see how it does.  Updates incoming soon.  Thanks for looking at it.

2024-01-24 02:42 UTC, myvaughn approved these changes
The changes look good from an accessibility standpoint.

2024-01-26 00:54 UTC, codechefmarc reviewed
Hey David! Sorry it took me a while to get back to this one. Since I've been a little out of the loop on the discussions, I'm not sure which components are excluded from the treatments so I tested all of the components you can add links to.

Test page here: https://pr-467-yalesites-platform.pantheonsite.io/marcs-test-page

Text block - all worked as expected. I see that external documents it defaults to the PDF and document treatment, not external.

As for the rest of the components, all worked except for the following ones with screenshots attached:

* tabs
* accordion
* gallery (caption links were completely stripped out)
* spotlight - CTA worked, links in body did not. (both kinds of spotlights)
* wrapped image (both body text and caption)
* image (caption)
* video (caption)
![tabs-external](https://github.com/yalesites-org/yalesites-project/assets/107938318/553628a2-9747-4c03-a1a0-8fb95ae52890)
![accordion-new-window](https://github.com/yalesites-org/yalesites-project/assets/107938318/d28e40b5-ee57-4606-9107-6de682715b03)
![gallery-links-stripped](https://github.com/yalesites-org/yalesites-project/assets/107938318/ef94718a-bfcf-4cfb-8c1c-84de60e630f0)
![spotlight-portrait-external](https://github.com/yalesites-org/yalesites-project/assets/107938318/9a864bcf-8da7-4d19-9c2d-554301ddb806)
![spotlight-landscape-new-window](https://github.com/yalesites-org/yalesites-project/assets/107938318/74cf94a0-87ce-4ee7-8e03-f2e886bc2f69)
![wrapped-image-new-window](https://github.com/yalesites-org/yalesites-project/assets/107938318/1e30d1d5-b4fa-4d3e-8d2b-9b01d52bd58c)
![video-with-caption-new-window](https://github.com/yalesites-org/yalesites-project/assets/107938318/53f688ec-8c45-4d2f-be95-4908b7dc7a06)
![image-with-caption-new-window](https://github.com/yalesites-org/yalesites-project/assets/107938318/cb9bca09-e618-4728-ab38-d3214e968e6f)

2024-02-01 18:05 UTC, joetower approved these changes
@dblanken-yale I tested this here, using the helpful page examples folks have made, and here https://github.com/yalesites-org/component-library-twig/pull/319. 

Everything is looking great 👍 💯

2024-02-02 21:30 UTC, merged