YALB-236: Dev Processes
yalesites-org/yalesites-project pull request #6
Opened 2022-04-10 18:08 UTC by nJim

## [YALB-236: Dev Processes](https://yaleits.atlassian.net/browse/YALB-236)

### Description of work
- Adds path to composer to the profile repo to allow local changes to be discovered.
- Removes the profile from composer `allowed-packages` as it is not helpful at this time.
- Adds a `setup.sh` script to automate local setup.
- Updates setup instructions to breakout profile and theme instructions.
- Creates a `development.md` file to explain common developer tasks.

### Functional testing steps:
- [ ] Review all of the new instructions for accuracy, completeness, and grammar.
- [ ] Clone this repository. Inside the repo execute the setup script and verify that the local dev environment is correctly build. `npm run setup` should create a lando site.
- [ ] Follow the instructions for adding a new contributed module to the profile.
  - [ ] Verify that the new module is listed in profile's composer.json file
  - [ ] Verify that the new module is available in the local Drupal site

2022-04-14 19:10 UTC, vinmassaro requested changes
Looks good, just a few nitpicks. Thanks!

2022-04-14 19:10 UTC, vinmassaro commented on docs/setup.md
> +Alternatively, developers can use a symbolic link or Composer local repositories to allow projects to be tracked in version control. Each option has pros and cons. Any solution using sub-modules shou
Can this be dropped now now since we have agreed to how we will manage this?

2022-04-14 19:16 UTC, vinmassaro commented on docs/setup.md
> +Alternatively, developers can use a symbolic link or Composer local repositories to allow projects to be tracked in version control. Each option has pros and cons. Any solution using sub-modules shou
Can this be dropped now now since we have agreed to how we will manage this?

2022-04-18 03:58 UTC, nJim commented on scripts/node/setup.sh
> +if [[ grep -qxF 'composer.lock' .git/info/exclude ]]; then
👍

2022-04-18 13:09 UTC, vinmassaro approved these changes

2022-04-18 16:39 UTC, dens0ne approved these changes
I thought I had approved this on Thursday, my bad. Great work Jim! 🚢

2022-04-18 17:00 UTC, merged