Ysp 306  block field updater
yalesites-org/yalesites-project pull request #661
Opened 2024-05-21 00:06 UTC by codechefmarc

## [YALB-XX: Title](https://yaleits.atlassian.net/browse/YALB-XX)

### Description of work
- Adds functionality bullet item
- Fixes this or that bullet item

### Functional testing steps:
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] ...

2024-05-22 18:07 UTC, dblanken-yale approved these changes
Really cool functionality.  I'll reset the Action Banner Content back so others can test this in the same way, but everything looks great.  And the code looks like we can extend it in the future with non-text fields by using your work as a template.

2024-06-17 15:04 UTC, nJim commented on web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
> +      - Devel
@codechefmarc I'm not sure ow this keeps creeping in. Can you remove this requirements and look for instances that crept into the codebase?

2024-06-17 15:13 UTC, nJim requested changes
Just one small change the on 'devel' dependency sneaking in. Everything else works as described. Great job. A couple of thoughts for future work:
-We may want to create an update all button
-We may want to include paragraphs, nodes, and other entities

2024-06-18 15:33 UTC, nJim approved these changes

2024-06-18 15:47 UTC, merged