JAKALA: Views block enhancements
yalesites-org/yalesites-project pull request #742
Opened 2024-08-27 19:54 UTC by nplowman

## [YALB-XX: Title](https://yaleits.atlassian.net/browse/YALB-XX)

### Description of work
- Adds optional exposed filter for Category on Views blocks.
- Adds optional exposed filter for Keyword Search on Views blocks.
- Adds optional exposed filter for Year on Views blocks that display Posts.
- 

### Functional testing steps:
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] ...

2024-08-28 20:04 UTC, nplowman commented on web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/NewsYearFilter.php
> +class NewsYearFilter extends InOperator {
We should refactor instances of the word "News" to use "Post" instead, to match the conventions already on the site.

2024-08-28 20:05 UTC, nplowman commented on web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
> +    'title' => t('News by Year'),
We should probably make this label just "Year" rather than "News by Year".

2024-09-04 16:13 UTC, nplowman commented
Here are the known issues Jakala is currently working on addressing:

- [ ] Extra "Category" dropdown field with Post Category terms is showing up on View showing Profiles, when "Show Category Filter" option is enabled.
- [ ] "Category Filter Label" field does not work on View showing Profiles.
- [ ] Category and Tags disappear from Teaser Cards after applying filters.
- [ ] "Show Thumbnails" option still needs to be added to the "Field Display" options in the Views block configuration.

2024-09-09 19:39 UTC, kara-franco requested changes
Amazing work! We reviewed as a group and have the following feedback: 

- [ ] The Show Year filter should dynamically display when the Post view is selected. 
<img width="609" alt="Screenshot 2024-09-09 at 2 45 10 PM" src="https://github.com/user-attachments/assets/6f9db95c-fc98-49a3-bd75-816edc427f74">

- [ ] After a user hits Apply, the view item's label dissapears. In the example below, the label should be Original 
<img width="1234" alt="Screenshot 2024-09-09 at 2 59 41 PM" src="https://github.com/user-attachments/assets/e80b176f-dea3-4b1c-bd34-e8155ced278a">

- [ ] The user flow is clunky adding additional labels. The dropdown does not appear immediately as it does when the user first clicks in. 
<img width="730" alt="Screenshot 2024-09-09 at 2 50 12 PM" src="https://github.com/user-attachments/assets/e9014f54-cebe-4b01-baa1-0ef132474641">

2024-09-11 16:12 UTC, nplowman commented
@dblanken-yale @kara-franco The issue with the tags/labels disappearing should be resolved now.

On this item: 

> The user flow is clunky adding additional labels. The dropdown does not appear immediately as it does when the user first clicks in.

Per our discussion earlier today, we are going to stick with "ChosenJS" for the multiselect for now since it is already being used elsewhere in the platform, even though we acknowledge it does have room for improvement in terms of accessibility. 
Instead we are going to just make the following change for now:

- [ ] Remove down caret icon from Multiselects on Views block filters. (This icon is giving the impression that this is an interactive button, when it is not)

I think other than that, the only other thing this pull request is waiting for is the frontend work for the "Show Thumbnail" field display option. I'll post to let you know when both of these updates have been made.

2024-09-12 17:00 UTC, nplowman commented
@kara-franco @dblanken-yale I believe all of the outstanding issues on this pull request should be addressed now.

2024-09-13 14:32 UTC, atiddei approved these changes
I have some feedback that are not show stoppers and can be updated in the future.

2024-09-13 15:21 UTC, dblanken-yale requested changes
We noticed the following happening on this page:  https://pr-742-yalesites-platform.pantheonsite.io/april-sept-test-page

Could we request the message there to be formatted a bit better?  Maybe like: "No results match: Business"?

![626b7a87-b922-4e62-9f24-d513ff09f92d](https://github.com/user-attachments/assets/2ae422bd-87f6-4f8a-9b12-d9783eb11d5a)

2024-09-13 15:40 UTC, dblanken-yale commented
@nplowman Also, it looks as if the "Show Thumbnail" is not respecting the option selected when editing again.  If you disable it, it seems to always appear re-selected when you edit again.

2024-09-13 16:17 UTC, kara-franco requested changes
Can you change the Apply text to black to pass color contrast reqs: 
<img width="742" alt="Screenshot 2024-09-13 at 12 17 23 PM" src="https://github.com/user-attachments/assets/b0b205bf-7d2c-4fe9-a1c9-c141459e1c56">

2024-09-13 16:25 UTC, atiddei commented
Suggestion for a progressive enhancement:

Consider adding an option to selecting category filtering controls in the custom view block to select all categories that are actively used in the site’s content. This option should be available in the dropdown menu for category selection.

Benefits:

Efficiency: Simplifies category selection for site builders.
User Experience: Reduces chances of “no results” for end users by ensuring all relevant categories are included.

Implementation Suggestion:
Include a “Assigned Only Items” option in the dropdown menu for category filters.

2024-09-16 14:02 UTC, nplowman commented
@kara-franco Button text issue should also be resolved now. 
![Screenshot 2024-09-16 at 8 01 18 AM](https://github.com/user-attachments/assets/f330e3f1-5f97-4d67-b7b5-360a689b9bba)

2024-09-16 20:23 UTC, nplowman commented
Spacing issue on the multiselect "no results" message should also be resolved now.
![Screenshot 2024-09-16 at 2 22 55 PM](https://github.com/user-attachments/assets/8517e4ba-3a7a-448b-933d-2a7eaab46ffe)

2024-09-16 20:29 UTC, nplowman commented
@kara-franco @dblanken-yale I think that all of the outstanding issues on this pull request should be resolved now. 
(With the exception of the future enhancement @atiddei suggested related to filtering out Taxonomy Terms from the multiselect that are not actively used in the site's content).

2024-09-16 20:56 UTC, dblanken-yale approved these changes

2024-09-16 20:57 UTC, kara-franco approved these changes

2024-09-16 20:57 UTC, merged

2024-09-18 18:28 UTC, yalesites commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on [GitHub release](https://github.com/yalesites-org/yalesites-project/releases/tag/v1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: