LIB: LibCal Embed
yalesites-org/yalesites-project pull request #827
Opened 2024-12-12 16:37 UTC by Studio-Tom

## [LIB: LibCal Embed]

### Description of work
- Adds LibCal daily single-library JS widget option to the Embed block
- Includes styling and JS overrides for required content formatting

### Functional testing steps:
- [ ] Create test page with sidebar
- [ ] Enable Embed block in sidebar
- [ ] Add script from LibCal (daily view, single library, no jQuery) to Embed block in sidebar
- [ ] Check button functionality, disabled links, and date/hour formatting rewrites

2025-01-15 20:55 UTC, dblanken-yale commented
@Studio-Tom I think I got it going with conditional jQuery.  Let me know how it fares for you.  The next thing I'd like to do is somehow break apart the JS/CSS from the embed output so we can easily edit those in their own files.  Do you mind trying to do that?  My guess is now that we have a way to know it's a LibCal embed, we should be able to add them.

2025-01-15 20:56 UTC, dblanken-yale commented
Also going to get this up to date with `develop` so you can have a multidev again.

2025-02-07 13:40 UTC, dblanken-yale requested changes
Nice work, although I'm seeing some config changes that I'm not expecting in the work you were doing.  I'm seeing local config changes, changes removing existing config happening as well.  Are you able to look into those and clean that part up?  Then we can properly review it.

2025-02-24 14:09 UTC, miketullo95 commented
@Studio-Tom if we can fix the text hover, we can hotfix this into production in the coming day or so. 

![Screenshot 2025-02-24 at 9 09 44 AM](https://github.com/user-attachments/assets/aa0f2293-c29c-4250-a32c-f85c7608bbe4)

2025-02-24 14:11 UTC, Studio-Tom commented
Thanks! That update should be ready later this morning.

2025-02-25 17:45 UTC, dblanken-yale commented
@Studio-Tom This looks good to go.  I'm going to attempt to move it to the master branch for the hotfix.  You should be able to let Monica know! Nice work!

2025-02-25 17:47 UTC, merged

2025-02-25 17:53 UTC, yalesites commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on [GitHub release](https://github.com/yalesites-org/yalesites-project/releases/tag/v1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: